pipeline {
    agent {
        docker {
            image 'maven:3.9.8'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Prepare') {
            steps {
                sh 'echo Preparing workspace...'
                cleanWs()
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
                success {
                    echo 'Tests passed successfully!'
                }
                failure {
                    echo 'Tests failed. Please check the test reports.'
                }
                unstable {
                    echo 'Some tests failed but the build is not marked as failed.'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
    }
}
